
/**
 * This is Account calss which stores data of the account
 * @author : Nitin Mankar
 * @since  : 08/14/2022
 */

import java.util.ArrayList;

public class Account {

    // type of account i.e. current,savings etc
    private String name ;

    // uuid of account
    private String uuid ;

    // the user object of this account
    private User holder ;

    // list of transactions
    private ArrayList<Transaction> transactions ;
    
    /**
     * explicit constructor
     * @param name      : type of bank account
     * @param holder    : instance of class User
     * @param theBank   : instance of class Bank
     */ 
    public Account (String name , User holder, Bank theBank){

        // type of account
        this.name = name ;

        // instance of class User
        this.holder = holder ;

        // account uuid generated by class Bank
        this.uuid = theBank.getNewAccountUUID ();

        //initializing transactions list
        this.transactions = new ArrayList<Transaction> ();

        // display message for account creation
        System.out.println("\nAccount created sucessfully...\nAccount number " + this.uuid);
    }
  
    // to access account uuid in other classes
    public String getUUID() {
        return uuid;
    }
    
    // generate summary line
    public String  getSummaryLine(){
        double balance = this.getBalance();
	    return String.format("%s : Rs %.02f : %s", this.uuid, balance, this.name);
    }
    
    // balance in account
    public double getBalance(){
        double balance = 0;
        for (Transaction t :this.transactions){
            balance += t.getMoney();
        }
        return balance ;
    }

    /**
     * add transactions
     * @param amount : money
     * @param memo   : memory of transaction
     */
    public void addTransaction(double amount, String memo) {
		Transaction newTrans = new Transaction(amount, memo, this);
		this.transactions.add(newTrans);	
	}
    
    // show transactions
    public void showTransactions(){
        if(transactions.size() == 0){
            System.out.println("No transaction");
        }
        for (Transaction t : transactions){
            t.transactionInfo();
        }
    }
    
    // user of this account
    public User getUser(){
        return this.holder;
    }
}

